@extends('layouts.store')

@section('content')
@php
  $appName = $s->store_name ?? '17G Delivery';
  $email   = $s->contact_email ?? '';
  $address = $s->contact_address ?? '';
  $effectiveDate = '2025-01-01';
@endphp

<section class="py-4 border-bottom" style="background:linear-gradient(90deg,var(--brand, #6c5ce7),var(--brand-2,#00c2ff));">
  <div class="container text-white">
    <div class="d-flex align-items-center justify-content-between flex-wrap">
      <div>
        <h1 class="h3 mb-1">Privacy Policy</h1>
        <div class="opacity-75">Last updated: {{ $effectiveDate }}</div>
      </div>
      <nav aria-label="breadcrumb" class="mt-2 mt-md-0">
        <ol class="breadcrumb mb-0">
          <li class="breadcrumb-item">
            <a class="link-light text-decoration-none" href="{{ route('store.index') }}">Home</a>
          </li>
          <li class="breadcrumb-item active text-white" aria-current="page">Privacy Policy</li>
        </ol>
      </nav>
    </div>
  </div>
</section>

<section class="py-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-9">

        <div class="card border-0 shadow-sm">
          <div class="card-body p-4 p-lg-5">

            <p class="text-muted">
              This Privacy Policy describes how <strong>{{ $appName }}</strong> ("we," "us," or "our")
              collects, uses, and shares your information when you use our mobile application
              and related services (collectively, the "Service").
            </p>

            {{-- 1 --}}
            <h4 class="mt-4 mb-2">1. Information We Collect</h4>
            <p>We collect the following types of information when you use our Service:</p>

            <h6 class="mt-3">a) Information You Provide</h6>
            <ul>
              <li><strong>Account Information:</strong> Full name, phone number, and email address when you register.</li>
              <li><strong>Delivery Address:</strong> Pickup and drop-off addresses you enter for each delivery order.</li>
              <li><strong>Profile Information:</strong> Profile photo (optional) and any other details you provide.</li>
            </ul>

            <h6 class="mt-3">b) Information Collected Automatically</h6>
            <ul>
              <li><strong>Location Data:</strong> We collect your real-time GPS location while the app is in use to process deliveries, assign drivers, and track delivery progress. Location collection stops when you close the app or disable location access.</li>
              <li><strong>Device Information:</strong> Device type, operating system version, unique device identifiers, and mobile network information.</li>
              <li><strong>Usage Data:</strong> Log data such as app interactions, timestamps, and crash reports to improve service performance.</li>
              <li><strong>Push Notification Tokens:</strong> A device token generated by Firebase Cloud Messaging (FCM) to send you delivery status notifications.</li>
            </ul>

            {{-- 2 --}}
            <h4 class="mt-4 mb-2">2. How We Use Your Information</h4>
            <p>We use the collected information to:</p>
            <ul>
              <li>Process and manage delivery orders</li>
              <li>Assign and coordinate with delivery drivers</li>
              <li>Send real-time delivery status updates via push notifications</li>
              <li>Display your order history and account details</li>
              <li>Improve, maintain, and secure the Service</li>
              <li>Respond to your support requests and communications</li>
              <li>Comply with applicable legal obligations</li>
            </ul>

            {{-- 3 --}}
            <h4 class="mt-4 mb-2">3. Sharing of Your Information</h4>
            <p>We do not sell your personal information. We may share your information with:</p>
            <ul>
              <li><strong>Delivery Drivers:</strong> Your name, phone number, and delivery address are shared with the assigned driver to complete your order.</li>
              <li><strong>Firebase (Google LLC):</strong> We use Firebase services for push notifications (FCM) and crash analytics. Data is processed according to <a href="https://policies.google.com/privacy" target="_blank" rel="noopener">Google's Privacy Policy</a>.</li>
              <li><strong>Business Partners:</strong> If you place an order through a merchant on our platform, relevant order details are shared with that merchant.</li>
              <li><strong>Legal Authorities:</strong> When required by law, court order, or to protect the rights and safety of our users and the public.</li>
            </ul>

            {{-- 4 --}}
            <h4 class="mt-4 mb-2">4. Data Retention</h4>
            <p>
              We retain your personal information for as long as your account is active or as needed to provide the Service.
              Order records are retained for accounting and legal compliance purposes.
              You may request deletion of your account and associated data by contacting us (see Section 8).
            </p>

            {{-- 5 --}}
            <h4 class="mt-4 mb-2">5. Data Security</h4>
            <p>
              We implement industry-standard security measures including encrypted data transmission (HTTPS/TLS),
              secure token-based authentication, and access controls to protect your personal information.
              However, no method of transmission over the internet is 100% secure.
            </p>

            {{-- 6 --}}
            <h4 class="mt-4 mb-2">6. Children's Privacy</h4>
            <p>
              Our Service is not directed to children under the age of 13. We do not knowingly collect personal
              information from children. If you believe a child has provided us with their information,
              please contact us so we can delete it.
            </p>

            {{-- 7 --}}
            <h4 class="mt-4 mb-2">7. Your Rights and Choices</h4>
            <ul>
              <li><strong>Access &amp; Correction:</strong> You may view and update your profile information within the app at any time.</li>
              <li><strong>Location Access:</strong> You can disable location permissions in your device settings. Note that location is required for core delivery functionality.</li>
              <li><strong>Push Notifications:</strong> You can opt out of push notifications through your device settings.</li>
              <li><strong>Account Deletion:</strong> You may request deletion of your account and personal data by contacting us.</li>
            </ul>

            {{-- 8 --}}
            <h4 class="mt-4 mb-2">8. Contact Us</h4>
            <p>If you have any questions about this Privacy Policy or how we handle your data, please contact us:</p>
            <address class="mb-0">
              <strong>{{ $appName }}</strong><br>
              @if($email)
                Email: <a href="mailto:{{ $email }}">{{ $email }}</a><br>
              @endif
              @if($address)
                Address: {{ $address }}
              @endif
            </address>

            {{-- 9 --}}
            <h4 class="mt-4 mb-2">9. Changes to This Policy</h4>
            <p>
              We may update this Privacy Policy from time to time. When we do, we will update the
              "Last updated" date at the top of this page and notify you through the app or via email
              for significant changes. Your continued use of the Service after changes constitutes
              acceptance of the updated policy.
            </p>

          </div>
        </div>

      </div>
    </div>
  </div>
</section>
@endsection
